version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: snake-build
    container_name: snake-build

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: snake-test
    depends_on:
      - build

  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    image: rafal206/snake-game:v1.0.3
    container_name: snake-app
    ports:
      - "8080:8080"